FROM jenkins/jenkins:lts

USER root

# Install Docker CLI only (not the daemon)
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean

# Allow Jenkins user to use Docker socket
RUN usermod -aG docker jenkins

USER jenkins
